<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: address_book/address_book.proto

namespace GPBMetadata\AddressBook;

class AddressBook
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a94030a1f616464726573735f626f6f6b2f616464726573735f626f6f6b" .
            "2e70726f746f224a0a0b50686f6e654e756d626572120e0a066e756d6265" .
            "7218012001280912180a047479706518022001280e320a2e50686f6e6554" .
            "79706512110a09657874656e73696f6e18032001280922c7010a06506572" .
            "736f6e120a0a026964180120012803120c0a046e616d6518022001280912" .
            "0d0a05656d61696c180320012809121c0a0670686f6e657318042003280b" .
            "320c2e50686f6e654e756d62657212230a047461677318052003280b3211" .
            "2e506572736f6e2e54616773456e7472794202180112110a096973426c6f" .
            "636b6564180620012808120b0a0361676518082001280d1a2b0a09546167" .
            "73456e747279120b0a036b6579180120012809120d0a0576616c75651802" .
            "200128093a0238014a040807100822260a0b41646472657373426f6f6b12" .
            "170a0670656f706c6518012003280b32072e506572736f6e2a2b0a095068" .
            "6f6e6554797065120a0a064d4f42494c45100012080a04484f4d45100112" .
            "080a04574f524b1002620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

