<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: address_book/address_book.proto

namespace GPBMetadata\AddressBook;

class AddressBook
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aea020a1f616464726573735f626f6f6b2f616464726573735f626f6f6b" .
            "2e70726f746f22370a0b50686f6e654e756d626572120e0a066e756d6265" .
            "7218012001280912180a047479706518022001280e320a2e50686f6e6554" .
            "79706522b0010a06506572736f6e120a0a026964180120012803120c0a04" .
            "6e616d65180220012809120d0a05656d61696c180320012809121c0a0670" .
            "686f6e657318042003280b320c2e50686f6e654e756d626572121f0a0474" .
            "61677318052003280b32112e506572736f6e2e54616773456e7472791211" .
            "0a096973426c6f636b65641806200128081a2b0a0954616773456e747279" .
            "120b0a036b6579180120012809120d0a0576616c75651802200128093a02" .
            "380122260a0b41646472657373426f6f6b12170a0670656f706c65180120" .
            "03280b32072e506572736f6e2a2b0a0950686f6e6554797065120a0a064d" .
            "4f42494c45100012080a04484f4d45100112080a04574f524b1002620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

