// Code generated by protoc-gen-go. DO NOT EDIT.
// source: address_book/address_book.proto

package address_book

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PhoneType int32

const (
	PhoneType_MOBILE PhoneType = 0
	PhoneType_HOME   PhoneType = 1
	PhoneType_WORK   PhoneType = 2
)

var PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}

var PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x PhoneType) String() string {
	return proto.EnumName(PhoneType_name, int32(x))
}

func (PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6b6da4d417e527ac, []int{0}
}

type PhoneNumber struct {
	Number               string    `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PhoneNumber) Reset()         { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()    {}
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b6da4d417e527ac, []int{0}
}

func (m *PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneNumber.Unmarshal(m, b)
}
func (m *PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneNumber.Merge(m, src)
}
func (m *PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_PhoneNumber.Size(m)
}
func (m *PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneNumber proto.InternalMessageInfo

func (m *PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *PhoneNumber) GetType() PhoneType {
	if m != nil {
		return m.Type
	}
	return PhoneType_MOBILE
}

type Person struct {
	Id                   int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string            `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phones               []*PhoneNumber    `protobuf:"bytes,4,rep,name=phones,proto3" json:"phones,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IsBlocked            bool              `protobuf:"varint,6,opt,name=isBlocked,proto3" json:"isBlocked,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b6da4d417e527ac, []int{1}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

func (m *Person) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Person) GetIsBlocked() bool {
	if m != nil {
		return m.IsBlocked
	}
	return false
}

type AddressBook struct {
	People               []*Person `protobuf:"bytes,1,rep,name=people,proto3" json:"people,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddressBook) Reset()         { *m = AddressBook{} }
func (m *AddressBook) String() string { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()    {}
func (*AddressBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b6da4d417e527ac, []int{2}
}

func (m *AddressBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressBook.Unmarshal(m, b)
}
func (m *AddressBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressBook.Marshal(b, m, deterministic)
}
func (m *AddressBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressBook.Merge(m, src)
}
func (m *AddressBook) XXX_Size() int {
	return xxx_messageInfo_AddressBook.Size(m)
}
func (m *AddressBook) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressBook.DiscardUnknown(m)
}

var xxx_messageInfo_AddressBook proto.InternalMessageInfo

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterEnum("PhoneType", PhoneType_name, PhoneType_value)
	proto.RegisterType((*PhoneNumber)(nil), "PhoneNumber")
	proto.RegisterType((*Person)(nil), "Person")
	proto.RegisterMapType((map[string]string)(nil), "Person.TagsEntry")
	proto.RegisterType((*AddressBook)(nil), "AddressBook")
}

func init() { proto.RegisterFile("address_book/address_book.proto", fileDescriptor_6b6da4d417e527ac) }

var fileDescriptor_6b6da4d417e527ac = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x51, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0xff, 0x69, 0xbb, 0xfc, 0xd7, 0x3b, 0x19, 0xf5, 0x22, 0x12, 0x44, 0x5c, 0x19, 0x0a,
	0x45, 0xa1, 0xc2, 0x7c, 0x50, 0x7c, 0x73, 0x50, 0x50, 0x74, 0x6e, 0x84, 0x81, 0x8f, 0xd2, 0xd9,
	0x30, 0x4b, 0xbb, 0x26, 0x34, 0x9d, 0xd0, 0x2f, 0xec, 0xe7, 0x90, 0xa6, 0x75, 0xee, 0xed, 0x9c,
	0x73, 0x7b, 0x9a, 0x5f, 0x6e, 0x60, 0x14, 0x27, 0x49, 0x29, 0xb4, 0x7e, 0x5f, 0x49, 0x99, 0x5d,
	0xef, 0x9b, 0x50, 0x95, 0xb2, 0x92, 0xe3, 0x08, 0x06, 0x8b, 0x4f, 0x59, 0x88, 0xd7, 0xed, 0x66,
	0x25, 0x4a, 0x3c, 0x06, 0x5a, 0x18, 0xc5, 0x88, 0x4f, 0x02, 0x97, 0x77, 0x0e, 0xcf, 0xc0, 0xa9,
	0x6a, 0x25, 0x98, 0xe5, 0x93, 0x60, 0x38, 0x81, 0xd0, 0x74, 0x96, 0xb5, 0x12, 0xdc, 0xe4, 0xe3,
	0x6f, 0x02, 0x74, 0x21, 0x4a, 0x2d, 0x0b, 0x1c, 0x82, 0x95, 0x26, 0xa6, 0x6e, 0x73, 0x2b, 0x4d,
	0x10, 0xc1, 0x29, 0xe2, 0x4d, 0x5b, 0x75, 0xb9, 0xd1, 0x78, 0x04, 0x3d, 0xb1, 0x89, 0xd3, 0x9c,
	0xd9, 0x26, 0x6c, 0x0d, 0x9e, 0x03, 0x55, 0xcd, 0x7f, 0x35, 0x73, 0x7c, 0x3b, 0x18, 0x4c, 0x0e,
	0xc2, 0x3d, 0x34, 0xde, 0xcd, 0xf0, 0x02, 0x9c, 0x2a, 0x5e, 0x6b, 0xd6, 0x33, 0xdf, 0x1c, 0x86,
	0xed, 0xb1, 0xe1, 0x32, 0x5e, 0xeb, 0xa8, 0xa8, 0xca, 0x9a, 0x9b, 0x31, 0x9e, 0x82, 0x9b, 0xea,
	0x69, 0x2e, 0x3f, 0x32, 0x91, 0x30, 0xea, 0x93, 0xa0, 0xcf, 0xff, 0x82, 0x93, 0x5b, 0x70, 0x77,
	0x05, 0xf4, 0xc0, 0xce, 0x44, 0xdd, 0xdd, 0xb8, 0x91, 0x0d, 0xdf, 0x57, 0x9c, 0x6f, 0x7f, 0xa1,
	0x5b, 0x73, 0x6f, 0xdd, 0x91, 0x71, 0x08, 0x83, 0x87, 0x76, 0x8b, 0x53, 0x29, 0x33, 0x1c, 0x01,
	0x55, 0x42, 0xaa, 0x5c, 0x30, 0x62, 0x70, 0xfe, 0x77, 0x38, 0xbc, 0x8b, 0x2f, 0xaf, 0xc0, 0xdd,
	0xed, 0x0a, 0x01, 0xe8, 0x6c, 0x3e, 0x7d, 0x7a, 0x89, 0xbc, 0x7f, 0xd8, 0x07, 0xe7, 0x71, 0x3e,
	0x8b, 0x3c, 0xd2, 0xa8, 0xb7, 0x39, 0x7f, 0xf6, 0xac, 0x15, 0x35, 0x6f, 0x72, 0xf3, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x49, 0x03, 0xed, 0xd8, 0xb6, 0x01, 0x00, 0x00,
}
