// Code generated by protoc-gen-go. DO NOT EDIT.
// source: address_book/address_book.proto

package address_book

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PhoneType int32

const (
	PhoneType_MOBILE PhoneType = 0
	PhoneType_HOME   PhoneType = 1
	PhoneType_WORK   PhoneType = 2
)

var PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}

var PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x PhoneType) String() string {
	return proto.EnumName(PhoneType_name, int32(x))
}

func (PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6b6da4d417e527ac, []int{0}
}

type PhoneNumber struct {
	Number               string    `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=PhoneType" json:"type,omitempty"`
	Extension            string    `protobuf:"bytes,3,opt,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PhoneNumber) Reset()         { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()    {}
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b6da4d417e527ac, []int{0}
}

func (m *PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneNumber.Unmarshal(m, b)
}
func (m *PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneNumber.Merge(m, src)
}
func (m *PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_PhoneNumber.Size(m)
}
func (m *PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneNumber proto.InternalMessageInfo

func (m *PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *PhoneNumber) GetType() PhoneType {
	if m != nil {
		return m.Type
	}
	return PhoneType_MOBILE
}

func (m *PhoneNumber) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

type Person struct {
	Id        int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email     string            `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phones    []*PhoneNumber    `protobuf:"bytes,4,rep,name=phones,proto3" json:"phones,omitempty"`
	Tags      map[string]string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // Deprecated: Do not use.
	IsBlocked bool              `protobuf:"varint,6,opt,name=isBlocked,proto3" json:"isBlocked,omitempty"`
	// string nickname = 7;
	Age                  uint32   `protobuf:"varint,8,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b6da4d417e527ac, []int{1}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

// Deprecated: Do not use.
func (m *Person) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Person) GetIsBlocked() bool {
	if m != nil {
		return m.IsBlocked
	}
	return false
}

func (m *Person) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type AddressBook struct {
	People               []*Person `protobuf:"bytes,1,rep,name=people,proto3" json:"people,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddressBook) Reset()         { *m = AddressBook{} }
func (m *AddressBook) String() string { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()    {}
func (*AddressBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b6da4d417e527ac, []int{2}
}

func (m *AddressBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressBook.Unmarshal(m, b)
}
func (m *AddressBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressBook.Marshal(b, m, deterministic)
}
func (m *AddressBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressBook.Merge(m, src)
}
func (m *AddressBook) XXX_Size() int {
	return xxx_messageInfo_AddressBook.Size(m)
}
func (m *AddressBook) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressBook.DiscardUnknown(m)
}

var xxx_messageInfo_AddressBook proto.InternalMessageInfo

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterEnum("PhoneType", PhoneType_name, PhoneType_value)
	proto.RegisterType((*PhoneNumber)(nil), "PhoneNumber")
	proto.RegisterType((*Person)(nil), "Person")
	proto.RegisterMapType((map[string]string)(nil), "Person.TagsEntry")
	proto.RegisterType((*AddressBook)(nil), "AddressBook")
}

func init() { proto.RegisterFile("address_book/address_book.proto", fileDescriptor_6b6da4d417e527ac) }

var fileDescriptor_6b6da4d417e527ac = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x51, 0xcf, 0x4b, 0xf3, 0x40,
	0x10, 0xfd, 0x36, 0x49, 0xd3, 0x64, 0xfa, 0x59, 0xe2, 0x22, 0xb2, 0x88, 0xd8, 0x50, 0x3c, 0x44,
	0x85, 0x08, 0xf5, 0xa0, 0x78, 0x33, 0x50, 0xf0, 0x57, 0x6d, 0x59, 0x0a, 0x1e, 0x25, 0x6d, 0x86,
	0x1a, 0x92, 0x66, 0x43, 0x36, 0x15, 0x73, 0xf5, 0x2f, 0x97, 0x6c, 0x62, 0xdb, 0xdb, 0x7b, 0x6f,
	0x66, 0xde, 0xbc, 0x9d, 0x85, 0x41, 0x18, 0x45, 0x05, 0x4a, 0xf9, 0xb1, 0x10, 0x22, 0xb9, 0xde,
	0x27, 0x7e, 0x5e, 0x88, 0x52, 0x0c, 0x97, 0xd0, 0x9b, 0x7d, 0x8a, 0x0c, 0xdf, 0x36, 0xeb, 0x05,
	0x16, 0xf4, 0x18, 0xcc, 0x4c, 0x21, 0x46, 0x5c, 0xe2, 0xd9, 0xbc, 0x65, 0xf4, 0x0c, 0x8c, 0xb2,
	0xca, 0x91, 0x69, 0x2e, 0xf1, 0xfa, 0x23, 0xf0, 0xd5, 0xcc, 0xbc, 0xca, 0x91, 0x2b, 0x9d, 0x9e,
	0x82, 0x8d, 0xdf, 0x25, 0x66, 0x32, 0x16, 0x19, 0xd3, 0xd5, 0xe8, 0x4e, 0x18, 0xfe, 0x68, 0x60,
	0xce, 0xb0, 0x90, 0x22, 0xa3, 0x7d, 0xd0, 0xe2, 0x48, 0x99, 0xeb, 0x5c, 0x8b, 0x23, 0x4a, 0xc1,
	0xc8, 0xc2, 0x75, 0x63, 0x6c, 0x73, 0x85, 0xe9, 0x11, 0x74, 0x70, 0x1d, 0xc6, 0x69, 0x6b, 0xd4,
	0x10, 0x7a, 0x0e, 0x66, 0x5e, 0x6f, 0x95, 0xcc, 0x70, 0x75, 0xaf, 0x37, 0xfa, 0xef, 0xef, 0x05,
	0xe7, 0x6d, 0x8d, 0x5e, 0x80, 0x51, 0x86, 0x2b, 0xc9, 0x3a, 0xaa, 0xe7, 0xd0, 0x6f, 0xd6, 0xfa,
	0xf3, 0x70, 0x25, 0xc7, 0x59, 0x59, 0x54, 0x81, 0xc6, 0x08, 0x57, 0x2d, 0x75, 0xe6, 0x58, 0x06,
	0xa9, 0x58, 0x26, 0x18, 0x31, 0xd3, 0x25, 0x9e, 0xc5, 0x77, 0x02, 0x75, 0x40, 0x0f, 0x57, 0xc8,
	0x2c, 0x97, 0x78, 0x07, 0xbc, 0x86, 0x27, 0xb7, 0x60, 0x6f, 0x6d, 0xea, 0x72, 0x82, 0x55, 0x7b,
	0xa5, 0x1a, 0xd6, 0xa9, 0xbf, 0xc2, 0x74, 0xf3, 0xf7, 0x94, 0x86, 0xdc, 0x6b, 0x77, 0xe4, 0xd9,
	0xb0, 0xba, 0x8e, 0x35, 0xf4, 0xa1, 0xf7, 0xd0, 0xdc, 0x3f, 0x10, 0x22, 0xa1, 0x03, 0x30, 0x73,
	0x14, 0x79, 0x8a, 0x8c, 0xa8, 0xa8, 0xdd, 0x36, 0x2a, 0x6f, 0xe5, 0xcb, 0x2b, 0xb0, 0xb7, 0x57,
	0xa6, 0x00, 0xe6, 0x64, 0x1a, 0x3c, 0xbd, 0x8e, 0x9d, 0x7f, 0xd4, 0x02, 0xe3, 0x71, 0x3a, 0x19,
	0x3b, 0xa4, 0x46, 0xef, 0x53, 0xfe, 0xe2, 0x68, 0x0b, 0x53, 0xfd, 0xe6, 0xcd, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x27, 0xdd, 0x8f, 0x27, 0xf0, 0x01, 0x00, 0x00,
}
