<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plane/plane.proto

namespace GPBMetadata\Plane;

class Plane
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae6020a11706c616e652f706c616e652e70726f746f22230a0b436f6f72" .
            "64696e6174657312090a017818012001280312090a017918022001280322" .
            "390a05506f696e7412210a0b636f6f7264696e6174657318012001280b32" .
            "0c2e436f6f7264696e61746573120d0a05636f756e74180220012804223e" .
            "0a06426f756e647312190a036d696e18012001280b320c2e436f6f726469" .
            "6e6174657312190a036d617818022001280b320c2e436f6f7264696e6174" .
            "657332a8010a05506c616e6512220a08476574506f696e74120c2e436f6f" .
            "7264696e617465731a062e506f696e74220012260a09507574506f696e74" .
            "73120c2e436f6f7264696e617465731a072e426f756e6473220028011229" .
            "0a124c697374506f696e74734279426f756e647312072e426f756e64731a" .
            "062e506f696e742200300112280a0a4c697374506f696e7473120c2e436f" .
            "6f7264696e617465731a062e506f696e74220028013001620670726f746f" .
            "33"
        ));

        static::$is_initialized = true;
    }
}

