<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plane/plane.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>Bounds</code>
 */
class Bounds extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Coordinates min = 1;</code>
     */
    private $min = null;
    /**
     * Generated from protobuf field <code>.Coordinates max = 2;</code>
     */
    private $max = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Coordinates $min
     *     @type \Coordinates $max
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Plane\Plane::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Coordinates min = 1;</code>
     * @return \Coordinates
     */
    public function getMin()
    {
        return $this->min;
    }

    /**
     * Generated from protobuf field <code>.Coordinates min = 1;</code>
     * @param \Coordinates $var
     * @return $this
     */
    public function setMin($var)
    {
        GPBUtil::checkMessage($var, \Coordinates::class);
        $this->min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Coordinates max = 2;</code>
     * @return \Coordinates
     */
    public function getMax()
    {
        return $this->max;
    }

    /**
     * Generated from protobuf field <code>.Coordinates max = 2;</code>
     * @param \Coordinates $var
     * @return $this
     */
    public function setMax($var)
    {
        GPBUtil::checkMessage($var, \Coordinates::class);
        $this->max = $var;

        return $this;
    }

}

