<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plane/plane.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>Coordinates</code>
 */
class Coordinates extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 x = 1;</code>
     */
    private $x = 0;
    /**
     * Generated from protobuf field <code>int64 y = 2;</code>
     */
    private $y = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $x
     *     @type int|string $y
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Plane\Plane::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 x = 1;</code>
     * @return int|string
     */
    public function getX()
    {
        return $this->x;
    }

    /**
     * Generated from protobuf field <code>int64 x = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setX($var)
    {
        GPBUtil::checkInt64($var);
        $this->x = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 y = 2;</code>
     * @return int|string
     */
    public function getY()
    {
        return $this->y;
    }

    /**
     * Generated from protobuf field <code>int64 y = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setY($var)
    {
        GPBUtil::checkInt64($var);
        $this->y = $var;

        return $this;
    }

}

