<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: address_book/address_book.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>Person</code>
 */
class Person extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string email = 3;</code>
     */
    private $email = '';
    /**
     * Generated from protobuf field <code>repeated .PhoneNumber phones = 4;</code>
     */
    private $phones;
    /**
     * Generated from protobuf field <code>map<string, string> tags = 5 [deprecated = true];</code>
     */
    private $tags;
    /**
     * Generated from protobuf field <code>bool isBlocked = 6;</code>
     */
    private $isBlocked = false;
    /**
     * string nickname = 7;
     *
     * Generated from protobuf field <code>uint32 age = 8;</code>
     */
    private $age = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $name
     *     @type string $email
     *     @type \PhoneNumber[]|\Google\Protobuf\Internal\RepeatedField $phones
     *     @type array|\Google\Protobuf\Internal\MapField $tags
     *     @type bool $isBlocked
     *     @type int $age
     *           string nickname = 7;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\AddressBook\AddressBook::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 3;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .PhoneNumber phones = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPhones()
    {
        return $this->phones;
    }

    /**
     * Generated from protobuf field <code>repeated .PhoneNumber phones = 4;</code>
     * @param \PhoneNumber[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPhones($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \PhoneNumber::class);
        $this->phones = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> tags = 5 [deprecated = true];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>map<string, string> tags = 5 [deprecated = true];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isBlocked = 6;</code>
     * @return bool
     */
    public function getIsBlocked()
    {
        return $this->isBlocked;
    }

    /**
     * Generated from protobuf field <code>bool isBlocked = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsBlocked($var)
    {
        GPBUtil::checkBool($var);
        $this->isBlocked = $var;

        return $this;
    }

    /**
     * string nickname = 7;
     *
     * Generated from protobuf field <code>uint32 age = 8;</code>
     * @return int
     */
    public function getAge()
    {
        return $this->age;
    }

    /**
     * string nickname = 7;
     *
     * Generated from protobuf field <code>uint32 age = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setAge($var)
    {
        GPBUtil::checkUint32($var);
        $this->age = $var;

        return $this;
    }

}

