<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: address_book/address_book.proto

/**
 * Protobuf type <code>PhoneType</code>
 */
class PhoneType
{
    /**
     * Generated from protobuf enum <code>MOBILE = 0;</code>
     */
    const MOBILE = 0;
    /**
     * Generated from protobuf enum <code>HOME = 1;</code>
     */
    const HOME = 1;
    /**
     * Generated from protobuf enum <code>WORK = 2;</code>
     */
    const WORK = 2;
}

