<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plane/plane.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>Point</code>
 */
class Point extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Coordinates coordinates = 1;</code>
     */
    private $coordinates = null;
    /**
     * Generated from protobuf field <code>uint64 count = 2;</code>
     */
    private $count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Coordinates $coordinates
     *     @type int|string $count
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Plane\Plane::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Coordinates coordinates = 1;</code>
     * @return \Coordinates
     */
    public function getCoordinates()
    {
        return $this->coordinates;
    }

    /**
     * Generated from protobuf field <code>.Coordinates coordinates = 1;</code>
     * @param \Coordinates $var
     * @return $this
     */
    public function setCoordinates($var)
    {
        GPBUtil::checkMessage($var, \Coordinates::class);
        $this->coordinates = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 count = 2;</code>
     * @return int|string
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>uint64 count = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkUint64($var);
        $this->count = $var;

        return $this;
    }

}

